package data;
// Generated 24.01.2018 13:17:30 by Hibernate Tools 4.3.1



/**
 * GewinnerId generated by hbm2java
 */
public class GewinnerId  implements java.io.Serializable {


     private int idGewinner;
     private int lotterieIdLotterie;

    public GewinnerId() {
    }

    public GewinnerId(int idGewinner, int lotterieIdLotterie) {
       this.idGewinner = idGewinner;
       this.lotterieIdLotterie = lotterieIdLotterie;
    }
   
    public int getIdGewinner() {
        return this.idGewinner;
    }
    
    public void setIdGewinner(int idGewinner) {
        this.idGewinner = idGewinner;
    }
    public int getLotterieIdLotterie() {
        return this.lotterieIdLotterie;
    }
    
    public void setLotterieIdLotterie(int lotterieIdLotterie) {
        this.lotterieIdLotterie = lotterieIdLotterie;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GewinnerId) ) return false;
		 GewinnerId castOther = ( GewinnerId ) other; 
         
		 return (this.getIdGewinner()==castOther.getIdGewinner())
 && (this.getLotterieIdLotterie()==castOther.getLotterieIdLotterie());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGewinner();
         result = 37 * result + this.getLotterieIdLotterie();
         return result;
   }   


}


