package ch.bbw.lotto;
// Generated 27.01.2018 13:30:46 by Hibernate Tools 4.3.1



/**
 * Gewinner generated by hbm2java
 */
public class Gewinner  implements java.io.Serializable {


     private GewinnerId id;
     private Lotterie lotterie;
     private String name;
     private String vorname;
     private Integer gewinn;

    public Gewinner() {
    }

	
    public Gewinner(GewinnerId id, Lotterie lotterie) {
        this.id = id;
        this.lotterie = lotterie;
    }
    public Gewinner(GewinnerId id, Lotterie lotterie, String name, String vorname, Integer gewinn) {
       this.id = id;
       this.lotterie = lotterie;
       this.name = name;
       this.vorname = vorname;
       this.gewinn = gewinn;
    }
   
    public GewinnerId getId() {
        return this.id;
    }
    
    public void setId(GewinnerId id) {
        this.id = id;
    }
    public Lotterie getLotterie() {
        return this.lotterie;
    }
    
    public void setLotterie(Lotterie lotterie) {
        this.lotterie = lotterie;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    public Integer getGewinn() {
        return this.gewinn;
    }
    
    public void setGewinn(Integer gewinn) {
        this.gewinn = gewinn;
    }




}


