package ch.bbw.lotto;
// Generated 27.01.2018 13:30:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lotterie generated by hbm2java
 */
public class Lotterie  implements java.io.Serializable {


     private int idLotterie;
     private String name;
     private Set<Gewinner> gewinners = new HashSet<Gewinner>(0);

    public Lotterie() {
    }

	
    public Lotterie(int idLotterie) {
        this.idLotterie = idLotterie;
    }
    public Lotterie(int idLotterie, String name, Set<Gewinner> gewinners) {
       this.idLotterie = idLotterie;
       this.name = name;
       this.gewinners = gewinners;
    }
   
    public int getIdLotterie() {
        return this.idLotterie;
    }
    
    public void setIdLotterie(int idLotterie) {
        this.idLotterie = idLotterie;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Gewinner> getGewinners() {
        return this.gewinners;
    }
    
    public void setGewinners(Set<Gewinner> gewinners) {
        this.gewinners = gewinners;
    }




}


